name: .NET 8.0 CI

on:
  push:
    branches: [ master ] 
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET 8.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Install dependencies
      run: dotnet restore Otus.Teaching.PromoCodeFactory.sln
      working-directory: src

    - name: Build
      run: dotnet build Otus.Teaching.PromoCodeFactory.sln --no-restore -c Release
      working-directory: src

    - name: Test
      run: dotnet test Otus.Teaching.PromoCodeFactory.sln --no-build --verbosity normal -c Release
      working-directory: src
